### ISSUE TITLE
Is it possible to use k6chaijs with async function? For example in browser tests?

### ISSUE THREAD

**Issue by aswarcewicz** [grafana/k6-jslib-k6chaijs#15]
I'd like to use k6chaijs with browser k6 module, but I have observed that messages are printed in wrong order.

For example this test function:

```
export default () => {
    describe('New page verifier', async () => {
        const page = await browser.newPage();
        try {
            expect(page, "page").to.be.null;
        } finally {
            await page.close();
        }
    })
}
```

Prints output like this:
```

     ✗ expected page to be null
      ↳  0% — ✓ 0 / ✗ 1

     █ New page verifier

   ✗ checks...............: 0.00% ✓ 0        ✗ 1  
     data_received........: 0 B   0 B/s
     data_sent............: 0 B   0 B/s

```

Text from describe function is after assertion what is not expected

**Comment by bdshadow** [comment]
since `describe` is the wrapper of a `group`, then it probably has the same issues with async. Check the big red warning here: https://grafana.com/docs/k6/latest/javascript-api/k6/group/:

> WARNING
Avoid using group with async functions or asynchronous code. If you do, k6 might apply tags in a way that is unreliable or unintuitive.
If you start promise chains or even use await within group, some code within the group will be waited for and tagged with the proper group tag, but others won’t be.
To avoid confusion, async functions are forbidden as group() arguments. This still lets users make and chain promises within a group, but doing so is unsupported and not recommended.
For more information, refer to [k6 #2728](https://github.com/grafana/k6/issues/2728), which tracks possible solutions and provides detailed explanations. 

P.S
I'm not a k6 developer, just bumped into the same issue while using it
